kind: pipeline
type: docker
name: default

steps:
  - name: build
    image: microsoft/dotnet:2.0-sdk
    commands:
      - dotnet build Grapute -c Release
    when:
      event: [push]

  - name: publish-nuget
    image: microsoft/dotnet:2.0-sdk
    environment:
      NUGETKEY:
        from_secret: NUGET_KEY
    commands:
      - dotnet build Grapute -c Release
      - dotnet pack Grapute -c Release -p:PackageVersion=2.0.0.$${DRONE_BUILD_NUMBER}
      - dotnet nuget push Grapute/bin/Release/Grapute.2.0.0.$${DRONE_BUILD_NUMBER}.nupkg -s https://api.nuget.org/v3/index.json -k $${NUGETKEY}
    when:
      event: [push]
      branch: [master]